version: '3.1'

services:
    teamcity:
        image: jetbrains/teamcity-server:2019.2.1
        volumes:
            - teamcity-server-datadir:/data/teamcity_server/datadir
            - teamcity-server-logs:/opt/teamcity/logs
        ports:
            - 8111:8111
    teamcity-agent:
        image: jetbrains/teamcity-agent:2019.2.1
        environment:
            SERVER_URL: http://teamcity:8111
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    my-registry:
        image: registry:2.6.1
        volumes:
            - registry:/var/lib/registry
        ports:
            - 55000:5000

volumes:
    teamcity-server-datadir:
    teamcity-server-logs:
    registry: